CLIMADA-project/climada_petals

climada_petals/__init__.py
climada_petals/util/config.py

This PR makes sure that the top-level logger `"climada_petals"` is set up correctly so that it's behavior agrees with that of the `"climada"` logger. Previously, the top-level logger wasn't set up at all so that all logging was propagated to the default root looger and used the configuration of that logger (whichever that was).
Additionally, this PR fixes the `CONFIG` object when using `climada_petals`. The previous attempts to overwrite CLIMADA's pre-defined `CONFIG` object in `climada_petals.util.config` cause several problems, especially the parallel existence of inconsistent `CONFIG` objects in the user namespace:
```
>>> from climada_petals.util.config import CONFIG
>>> CONFIG.hazard.drought
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: …
```

Fix logging and CONFIG in petals

---

climada_petals/entity/exposures/openstreetmap/osm_dataloader.py

Just a very minor fix to get rid of the following deprecation warning when calling `OSMApiQuery().get_data_overpass`
```
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
data=np.array([data_id,data_geom,data_tags]).T,
```

remove ragged nested sequence in np.array

---

climada_petals/hazard/tc_tracks_forecast.py

For the named TC from ECMWF ensemble forecast (e.g. TIFFANY and CODY at the time this pull request is made), the FTP folder provides an extra bufr files (name pattern `*ECMF*`) that _**only**_ contains the high resolution deterministic forecast track (ensemble id. 52). However, this track is also included in the regular bufr file that contains the full set of ensemble forecasts (ensemble id. 1-52). The current method reads all the TC bufr files and therefore, the deterministic forecast track with ensemble id 52 would duplicate. 
An update of this pull request that adds an argument `read_det` with default set to `False` that reads only the ensemble forecast (the bufr file that contains track with ensemble id 1-52). If set to `True` then it reads all the available bufr files from the FTP …

Adding argument to discard duplicate tracks

---

climada_petals/hazard/tc_surge_bathtub.py
climada_petals/hazard/test/test_tc_surge_bathtub.py

This fixes the tests for tc_surge_bathtub according to the changes to the function `read_raster_bounds` in the core repository (https://github.com/CLIMADA-project/climada_python/pull/339).

Fix tc_surge_bathtub tests for climada_python#339

---

climada_petals/hazard/river_flood.py
climada_petals/hazard/test/test_flood.py

This fixes a small bug where `event_id` would always start at 0 in `RiverFlood`. According to [the docs](https://climada-python.readthedocs.io/en/stable/climada/climada.hazard.html?highlight=check#climada.hazard.base.Hazard.event_id) of the `Hazard` base class, `event_id` is supposed to be greater zero. The bug prevented, e.g., plotting the hazard intensity of the first event, because `plot_intensity(event=0)` plots the maximum intensity over all events [by convention](https://climada-python.readthedocs.io/en/stable/climada/climada.hazard.html?highlight=check#climada.hazard.base.Hazard.plot_intensity).
There are two minor issues one might like to discuss:
* This problem is not detected by the `check()` method.
* The `check()` method is never executed in the `RiverFlood` unit tests.

Fix event_id starting at 0 in RiverFlood

---

climada_petals/hazard/test/test_low_flow.py

This PR is fixing the small recent discrepancies in the `LowFlow.from_netcdf` means comparison

test_low_flow: increase tolerance when comparing means

---

climada_petals/hazard/tc_surge_bathtub.py

This PR greatly improves the performance of the sparse matrix operations in the tc_surge_bathtub hazard module. It reduces the amount of memory required during the computation and for storing the result, and it reduces the computational time considerably. No functionality, and hence no unit tests are affected by these changes.
More details in the comments below.

tc_surge_bathtub: improve performance of sparse matrix operations

---

climada_petals/engine/test/test_warn.py
climada_petals/engine/warn.py

This pull requests fixes #69 
the function `Warn.zeropadding` was adopted to now deal with cases where the inputed non-rectangular map contains several non touching areas like islands. This produced an IndexError before. A test is added to check that such islands are handled correctly.
As it was already the case beforehand, the function assumes that the inputed non-rectangular map contains lat and lon values, that can be accurately represented as a regular grid. It now also checks for this assumption with a maximally allowed relative error in terms of grid resolution. This check is also tested.

fix issue #69 Warn.zeropadding for islands

---

CHANGELOG.md
climada_petals/hazard/river_flood.py
climada_petals/hazard/test/test_flood.py

- Since shapely 2.0, `MultiPolygon`s are not iterable anymore. therefore this PR suggests to use their `geoms` attribute as arguments when we the raster is set in `from_nc`.
This PR fixes #79

Replace MultiPolygon with MultiPolygon.geoms for Iterability

---

climada_petals/hazard/tc_tracks_forecast.py
climada_petals/hazard/test/test_tc_tracks_forecast.py

- cast "time" values to `float` when reading bufr file in `read_one_bufr_tc`
I suspect that with climada_python PR [#735](https://github.com/CLIMADA-project/climada_python/pull/735) time values are of dtype float when read from hdf5 (which makes sense too). But so far `time` has been an int.
This PR fixes failing of `climada_petals.hazard.test.test_tc_tracks_forecast.TestECMWF.test_hdf5_io` due to type differences in `tc_track` from bufr file and `tc_read` from hdf5
[linter]: https://climada-python.readthedocs.io/en/latest/guide/Guide_Continuous_Integration_and_Testi …

Adapt tc_forecast to climada_python improved hdf5 IO

---

setup.py

This fixes an issue where pip would not match 'climada==3.3' to, .e.g. v3.3.2.
This PR fixes this error:
```
$ pip check
climada-petals 3.3.1 has requirement climada==3.3, but you have climada 3.3.2.
```
which appears in https://github.com/conda-forge/staged-recipes/pull/23463

Use version matching for climada dependency

---

climada_petals/entity/exposures/openstreetmap/osm_dataloader.py
climada_petals/entity/exposures/test/test_spamagrar_unit.py
climada_petals/hazard/emulator/stats.py
climada_petals/hazard/low_flow.py
climada_petals/hazard/wildfire.py

- necessary adaptations for upgrading pandas to >=2.x
This PR fixes #[climada_python #700](https://github.com/CLIMADA-project/climada_python/issues/700)

Upgrade to Pandas 2.x

---

climada_petals/hazard/river_flood.py
climada_petals/hazard/tc_rainfield.py

- implicit casting to integer when calling `dt.datetime()`
This PR fixes #96

implicit casting for dt.datetime

---

AUTHORS.md
CHANGELOG.md
requirements/env_climada.yml

- Set `nodefaults` channel in environment specs
This PR fixes https://github.com/CLIMADA-project/climada_python/issues/843 and follows-up on the equivalent PR in the Core package, https://github.com/CLIMADA-project/climada_python/pull/845.

Avoid default Anaconda channel for environment

---

CHANGELOG.md
climada_petals/hazard/low_flow.py
climada_petals/hazard/test/test_wildfire.py
climada_petals/hazard/wildfire.py

* Use intermediate variables if LIL matrices are used.
* Write all-zero fraction matrix instead of all-ones (all-zero fractions are treated as ones).
This PR fixes compatibility issues arising from CLIMADA-project/climada_python#893

Only assign csr matrices to Hazard objects

---

script/jenkins/install_env.sh
setup.py

- Adjust doc and config file so that they point to python 3.11 as the default version
This PR fixes #

default installation with python 3.11

---

CHANGELOG.md
climada_petals/conf/climada.conf
climada_petals/hazard/copernicus_interface/downloader.py

This is one part of the `copernicus_interface` module that is currently under development (see PR #142).
- Added function `download_data` to `climada_petals.hazard.copernicus_interface` module that accesses a Copernicus data store and downloads a dataset with user-given parameter ranges.
Notes and questions:
- We have thought about what unit tests to write but, expect for some type checking of the input parameters, we could not think of a useful unit test. We do not want the unit test to actually access a datastore. Any suggestions welcome!
[linter]: …

Added function to download data from Copernicus data stores

---

CHANGELOG.md
climada_petals/hazard/test/test_tc_rainfield.py
climada_petals/hazard/test/test_tc_surge_bathtub.py

- This updates the test which requiresto use the ibtraca file which changed its name in PR https://github.com/CLIMADA-project/climada_python/pull/976 on climada core.

Update use of IBtracs file.

---

climada_petals/hazard/tc_rainfield.py

In https://github.com/CLIMADA-project/climada_python/pull/936 we change the approach for the `cyclostrophic` argument (as suggested in https://github.com/CLIMADA-project/climada_python/issues/897).
This patch updates the convention within petals for compatibility.

Updates `compute_angular_windspeeds` to match new cyclostrophic argument approach

---

CHANGELOG.md
climada_petals/hazard/tc_tracks_forecast.py
requirements/env_climada.yml

- Add lxml as explicit dependency
This PR is needed because `pandas-datareader` was hiding the requirement in Petals. See https://github.com/CLIMADA-project/climada_python/pull/1033, where the Petals compatibility tests fail. 

Add lxml dependency

---

climada_petals/entity/exposures/black_marble.py

- use unary_union instead
This PR fixes https://github.com/CLIMADA-project/climada_python/issues/1040

shapely.ops.cascaded_union removed in shapely 2.1
